---

- hosts: all
  become: true
  tasks: 

   
  - name: install apache and php  packages
    tags: always 
      
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: copy default html file for site
    tags: always
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install maria db on ubuntu
    tags: db,mariadb,ubuntu 
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"
 
